refactor: delete 로직 수정(optional, stream 사용)
lhh7985/SpringbootWebProject pull request #3
Opened 2020-11-17 04:07 UTC by lhh7985

@HwanChang
Optional과 Stream을 사용해서 수정해보았는데 이런 방식을 말씀하신 건지 아니면 지금 코드를 조금 더 수정해야 하는지 
조언 부탁드려도 될까요
if문 자체도 filter를 사용해야 할까요?

2020-11-17 05:08 UTC, HwanChang approved these changes
API 사용법은 이해한게 보이네요.
각 API에서 사용가능한 메소드들을 찾아보고 어떤경우에 사용될지 생각해본 다음 예제를 찾아보면 적용법을 익히는데 도움이 될거에요.

2020-11-17 05:08 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/service/CustomerService.java
> +			result = 1;
조건문 자체도 filter를 사용하다면 더 깔끔하게 작성이 가능할거같아요.
Optional을 이용해서 지금처럼 null 체크를 한다면 Optional을 쓰는 이점을 많이는 못가져가는거 같아 보여요.
구현방법은 여러가지가 있으니 정답이 있는건 아닙니다.
지금 코드도 이전에 비해서 확실히 깔끔해졌어요. 👍👍

2020-11-17 05:08 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		mapper.insertCode(insertCodeDTO);
추가로 이런 요청에 대한 값들의 검증을 어떻게 하면 좋을지 고민해보세요.

2020-11-17 07:33 UTC, lhh7985 commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		mapper.insertCode(insertCodeDTO);
Optional이 NullPointException을 처리하는데 좋다고 이해하고 있는데
insert, update, delete 같은 경우에는 실패하더라도 리턴 값이 레코드의 수인 0이 리턴되는데 
만약 Null이 발생하지 않는 리턴값에는 굳이 Optional을 사용하지 않고 int로 받아도 될까요?

2020-11-17 08:51 UTC, lhh7985 commented on First-Project2/src/main/java/com/ho/hwang/controller/AdminController.java
> +		}
제가 잘 이해했는지 예시로 코드를 작성해 보았습니다.
리턴값이 void인 경우 정상적으로 완료했는지 알수없기 때문에 리턴 값을 주고 최종적으로 컨트롤러에서 
HttpStatus를 정해주는 것이 맞는지 궁금합니다.

제가 Message클래스를 만들어서 리턴타입으로 전달하고 있는데 이 객체를 사용해서 또 다른 검증작업을 해야하는지
궁급합니다.

2020-11-18 02:06 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		mapper.insertCode(insertCodeDTO);
해당 쿼리들도 실행 후 결과를 받아와서 어떤 데이터를 insert, update, delete 했는지 리턴해주면 더 좋을거같아요.
그게 아니라면 boolean으로 성공/실패를 체크해주는게 int 보다는 훨씬 나아보이네요.

2020-11-19 00:16 UTC, HwanChang reviewed
전체적으로 아직 변수 네이밍이 수정안된게 많은거같아요.
여러군데에서 쓰게될 변수인데 나중에 수정하기보단 먼저 수정해두는게 추후에 귀찮은 일이 줄어들어 더 나을거같네요.

2020-11-19 00:16 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		return insertCodeDTO;
이부분도 마찬가지로 DTO를 리턴하기 보다는 insert한 code에 대한 정보를 vo로 담아서 리턴해주면 좋을거같아요.

2020-11-19 00:54 UTC, lhh7985 commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		return insertCodeDTO;
데이터의 입력은 DTO로 하지만 리턴은 VO로 받아야 하나요?

DTO로 리턴한 이유는 DTO를 parameter로 주게 되면 selectkey를 통해서 해당키 값을 리턴하고 set할 수 있어서였습니다.

VO로 리턴하려면 select문을 한번더 실행해야 할텐데, 모든 insert나 update에 select가 또 들어가면 성능이나 그런부분에서는 문제되는 일은 없나요? 아니면 일관성을 유지하기 위해서 select를 한번더 수행하는게 더 좋은 방법인가요?

2020-11-24 07:49 UTC, HwanChang reviewed
디테일한 부분에서 놓치고 있는 걸 몇가지 체크해봤으니 수정 방법을 고민해보세요.

그리고 커밋 범위를 최소 단위로 줄여서 하나의 PR에서 관련없는 작업도 함께 이루어지지 않도록 관리해주세요.

2020-11-24 07:49 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/controller/CustomerController.java
> +		EmployeeVO sales = userService.selectEmployee(customerDetail.getEmployee_id_sales());
각각 조회를 controller가 아닌 service 단에서 해주면 지금이랑 어떤 차이가 있을까요?

2020-11-24 07:49 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/controller/CustomerController.java
> +		Page paging = new Page(listCnt, page);
페이징 기능을 추가 하면 모든 리스트 조회에서 쓰게 될텐데 추후 유지보수를 위해 코드 중복을 줄일 방법을 고민해보세요.

2020-11-24 07:49 UTC, hwanchang commented on First-Project2/src/main/java/com/ho/hwang/controller/CustomerController.java
> +		SrVO srvo = srService.selectSRDetail(sr_id);
조회 결과가 null이라면 front 단에서 문제가 발생하지 않을까요?

2020-11-24 07:49 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/service/CustomerService.java
>  		int x = mapper.selectCustomer_id();
변수명은 의미를 알아볼 수 있게 짓도록 신경써야해요.

2020-11-26 06:25 UTC, HwanChang requested changes
네이밍은 적절하게 잘 수정됐어요.

몇가지 수정이 더 필요한 사항이 있어서 체크해봤으니 확인해주세요.

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/controller/ActivityController.java
> +		return new ResponseEntity<>(insertMessage, HttpStatus.OK);
세줄을 한줄로 줄여주면 더 깔끔하겠네요.

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/controller/ActivityController.java
>  	@PostMapping("/enroll-sr")
URL에 꼭필요하면 하이픈을 사용하지만 그렇지 않을경우 되도록이면 하이픈도 안쓰는게 좋을거같아요.

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/controller/CustomerController.java
> +			}
Optional을 사용한만큼 Optional의 장점을 좀 더 활용하는 방법을 찾아보세요.

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/dto/Activity/InsertCustomerActivityDto.java
> +    private Date activityRegistrationDate;
요즘은 Date 클래스 사용은 지양하고 있습니다.
아래 블로그 참고해주세요. (아래 블로그 외에 관련내용 검색해보면 다양한 정보 확인 가능합니다.)
[https://madplay.github.io/post/reasons-why-javas-date-and-calendar-was-bad](url)

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/service/CustomerService.java
> +		insertCustomerDto.setCustomerId(customerID);
이 부분도 네이밍 수정이 필요할거 같아요.

2020-11-26 06:25 UTC, HwanChang commented on First-Project2/src/main/java/com/ho/hwang/service/UserService.java
> +		}
여기도 Optional을 적절하게 사용하면 코드가 더 깔끔해질 것 같아요.

2020-12-03 05:58 UTC, merged